# Generate backend configuration files for other layers

# Network layer backend config
resource "local_file" "network_backend_config" {
  content = <<-EOT
# Network Layer Backend Configuration
# Auto-generated by bootstrap - do not edit manually

terraform {
  backend "s3" {
    bucket  = "${module.s3_backend.bucket_name}"
    key     = "network/terraform.tfstate"
    region  = "${var.region}"
    encrypt = true
  }
}
EOT
  filename = "${path.module}/../01-network/backend.tf"
}

# Compute layer backend config
resource "local_file" "compute_backend_config" {
  content = <<-EOT
# Compute Layer Backend Configuration
# Auto-generated by bootstrap - do not edit manually

terraform {
  backend "s3" {
    bucket  = "${module.s3_backend.bucket_name}"
    key     = "compute/terraform.tfstate"
    region  = "${var.region}"
    encrypt = true
  }
}
EOT
  filename = "${path.module}/../02-ec2-creation/backend.tf"
}
