# Compute Layer - EC2 Instances and Compute Resources

terraform {
  # Backend configuration will be generated by bootstrap
  # The backend.tf file will be created by backend-generator.tf in 00-bootstrap
}

# Network Data Source
# Get network information from the network layer
data "terraform_remote_state" "network" {
  backend = "s3"
  config = {
    bucket = var.network_state_bucket
    key    = "network/terraform.tfstate"
    region = var.aws_region
  }
}

# Security Group
resource "aws_security_group" "ec2_sg" {
  name        = "${var.project_name}-sg"
  description = "Security group for EC2"
  vpc_id      = data.terraform_remote_state.network.outputs.vpc_id

  ingress {
    description = "Allow SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project_name}-sg"
  }
}

# EC2 Instance Resource
resource "aws_instance" "this" {
  ami           = var.ami_id
  instance_type = var.instance_type
  key_name      = var.key_name
  subnet_id     = data.terraform_remote_state.network.outputs.public_subnet_id

  tags = {
    Name = var.instance_name
  }
}
