# Packer Layer - IAM Role for Packer AMI Building

terraform {
  # Backend configuration will be generated by bootstrap
  # The backend.tf file will be created by backend-generator.tf in 00-bootstrap
}

# IAM Role and Instance Profile for Packer
module "iam_packer" {
  source = "../modules/iam-ec2"

  project_name          = var.project_name
  environment           = var.environment
  enable_custom_policies = true
  
  policies = {
    packer = file("${path.module}/../iam/packer-policy.json")
  }
  
  common_tags = local.common_tags
}
