name: Terraform Setup
description: Setup Terraform with configurable version
inputs:
  terraform_version:
    description: 'Terraform version to install'
    required: false
    default: '1.10.0'
runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
