# Network Layer - VPC and Networking Infrastructure

terraform {
  # Backend configuration will be generated by bootstrap
  # The backend.tf file will be created by backend-generator.tf in 00-bootstrap
}

# Network Module
module "network" {
  source = "../modules/network"

  project_name        = var.project_name
  environment         = var.environment
  vpc_cidr            = var.vpc_cidr
  public_subnet_cidr  = var.public_subnet_cidr
  private_subnet_cidr = var.private_subnet_cidr
  availability_zone   = var.availability_zone
  common_tags         = local.common_tags
}
