# Nginx EC2 Layer - EC2 Instances with Nginx AMI

terraform {
  # Backend configuration will be generated by bootstrap
  # The backend.tf file will be created by backend-generator.tf in 00-bootstrap
}

# Network Data Source
data "terraform_remote_state" "network" {
  backend = "s3"
  config = {
    bucket = var.network_state_bucket
    key    = "network/terraform.tfstate"
    region = var.aws_region
  }
}

# Get Nginx AMI ID from SSM Parameter Store
# The AMI ID is written to SSM by CI/CD after Packer builds the AMI
data "aws_ssm_parameter" "nginx_ami_id" {
  name = "/${var.project_name}/${var.environment}/nginx-ami-id"

  # Validate that the parameter exists
  # This will fail with a clear error if the AMI hasn't been built yet
}

# IAM Role and Instance Profile for EC2
module "iam_ec2" {
  source = "../modules/iam-ec2"

  project_name           = var.project_name
  environment            = var.environment
  enable_managed_policies = length(var.policy_arns) > 0
  policy_arns            = var.policy_arns
  common_tags            = local.common_tags
}

# Security Group
resource "aws_security_group" "nginx_sg" {
  name        = "${var.project_name}-nginx-sg"
  description = "Security group for Nginx EC2 instances"
  vpc_id      = data.terraform_remote_state.network.outputs.vpc_id

  tags = merge(
    local.common_tags,
    {
      Name = "${var.project_name}-nginx-sg"
    }
  )
}

# Ingress Rule - Allow HTTP
resource "aws_vpc_security_group_ingress_rule" "http" {
  security_group_id = aws_security_group.nginx_sg.id
  description       = "Allow HTTP"
  from_port         = 80
  to_port           = 80
  ip_protocol       = "tcp"
  cidr_ipv4         = "0.0.0.0/0"
}

# Ingress Rule - Allow HTTPS
resource "aws_vpc_security_group_ingress_rule" "https" {
  count = var.enable_https ? 1 : 0

  security_group_id = aws_security_group.nginx_sg.id
  description       = "Allow HTTPS"
  from_port         = 443
  to_port           = 443
  ip_protocol       = "tcp"
  cidr_ipv4         = "0.0.0.0/0"
}


# Egress Rule - Allow all outbound
resource "aws_vpc_security_group_egress_rule" "all_outbound" {
  security_group_id = aws_security_group.nginx_sg.id
  description       = "Allow all outbound"
  from_port         = 0
  to_port           = 0
  ip_protocol       = "-1"
  cidr_ipv4         = "0.0.0.0/0"
}

# Launch Template
resource "aws_launch_template" "nginx" {
  name_prefix   = "${var.project_name}-nginx-"
  image_id      = data.aws_ssm_parameter.nginx_ami_id.value
  instance_type = var.instance_type

  vpc_security_group_ids = [aws_security_group.nginx_sg.id]

  iam_instance_profile {
    name = module.iam_ec2.instance_profile_name
  }

  user_data = var.user_data != "" ? base64encode(var.user_data) : null

  tag_specifications {
    resource_type = "instance"
    tags = merge(
      local.common_tags,
      {
        Name = var.instance_name
      }
    )
  }

  tags = merge(
    local.common_tags,
    {
      Name = "${var.project_name}-nginx-launch-template"
    }
  )

  lifecycle {
    # Validate AMI ID format and provide helpful error if missing
    precondition {
      condition     = can(regex("^ami-[0-9a-f]{17}$", data.aws_ssm_parameter.nginx_ami_id.value))
      error_message = "Invalid AMI ID in SSM parameter /${var.project_name}/${var.environment}/nginx-ami-id. Ensure the AMI has been built with Packer and the AMI ID has been stored in SSM Parameter Store."
    }
  }
}

# Auto Scaling Group
resource "aws_autoscaling_group" "nginx" {
  name                = "${var.project_name}-nginx-asg"
  vpc_zone_identifier = [data.terraform_remote_state.network.outputs.private_subnet_id]
  min_size            = var.min_size
  max_size            = var.max_size
  desired_capacity    = var.desired_capacity

  launch_template {
    id      = aws_launch_template.nginx.id
    version = "$Latest"
  }

  # EC2 health checks only verify the instance is running (no AMI configuration needed)
  # Use ELB health checks only if you have a load balancer with health check endpoints configured
  health_check_type         = var.health_check_type
  health_check_grace_period = var.health_check_grace_period

  tag {
    key                 = "Name"
    value               = var.instance_name
    propagate_at_launch = true
  }

  dynamic "tag" {
    for_each = local.common_tags
    content {
      key                 = tag.key
      value               = tag.value
      propagate_at_launch = true
    }
  }
}
